- hosts: all
  gather_facts: false
  tasks:

    - name: Install software packages
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      loop:
          - apt-transport-https
          - ca-certificates
          - curl
          - gpg

    - name: Creating k8s apt source list file and keyring file
      file:
        path: "{{ item }}"
        state: touch
        mode: '0644'
        owner: root
      loop:
        - /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        - /etc/apt/sources.list.d/kubernetes.list

    - name: Download Public signing Key for K8s repositories
      shell: |
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | sudo gpg --batch --no-tty --yes --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list

    - name: Install kubelet, kubeadm and kubectl
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - kubelet
        - kubeadm
        - kubectl

    - name: Prevent Kubernetes packages from being upgraded
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubelet
        - kubeadm
        - kubectl

    - name: Restart services 
      shell: |        
        systemctl daemon-reload
        systemctl restart kubelet
        systemctl restart containerd
